FROM confluentinc/cp-kafka-connect-base:5.5.0

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest 

RUN ls /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/

RUN env

