name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag strimzi-kafka-connect:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile.sink --tag kafka-connect-sink:$(date +%s)
